CRITICAL - 2021-02-15 00:37:22 --> Argument 1 passed to CodeIgniter\Model::doProtectFields() must be of the type array, string given, called in /var/www/system/Model.php on line 845
#0 /var/www/system/Model.php(845): CodeIgniter\Model->doProtectFields('Hendra Ramadani')
#1 /var/www/app/Controllers/User.php(54): CodeIgniter\Model->update(Array, 'Hendra Ramadani')
#2 /var/www/system/CodeIgniter.php(914): App\Controllers\User->update(NULL)
#3 /var/www/system/CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 /var/www/system/CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /var/www/public/index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-15 00:37:42 --> Argument 1 passed to CodeIgniter\Model::doProtectFields() must be of the type array, string given, called in /var/www/system/Model.php on line 845
#0 /var/www/system/Model.php(845): CodeIgniter\Model->doProtectFields('Hendra Ramadani')
#1 /var/www/app/Controllers/User.php(54): CodeIgniter\Model->update(Array, 'Hendra Ramadani')
#2 /var/www/system/CodeIgniter.php(914): App\Controllers\User->update(NULL)
#3 /var/www/system/CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 /var/www/system/CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /var/www/public/index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-15 00:38:01 --> Argument 1 passed to CodeIgniter\Model::doProtectFields() must be of the type array, string given, called in /var/www/system/Model.php on line 845
#0 /var/www/system/Model.php(845): CodeIgniter\Model->doProtectFields('Hendra Ramadani')
#1 /var/www/app/Controllers/User.php(54): CodeIgniter\Model->update(Array, 'Hendra Ramadani')
#2 /var/www/system/CodeIgniter.php(914): App\Controllers\User->update(NULL)
#3 /var/www/system/CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 /var/www/system/CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /var/www/public/index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-15 00:52:36 --> There is no data to {0}.
#0 /var/www/system/Model.php(809): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 /var/www/app/Controllers/User.php(55): CodeIgniter\Model->update(Array)
#2 /var/www/system/CodeIgniter.php(914): App\Controllers\User->update(NULL)
#3 /var/www/system/CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 /var/www/system/CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /var/www/public/index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-15 01:00:23 --> Trait 'CodeIgniter\API\RequestTrait' not found
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-02-15 02:02:20 --> Trait 'CodeIgniter\API\RequestTrait' not found
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-02-15 02:02:25 --> Trait 'CodeIgniter\API\RequestTrait' not found
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
